### ISSUE TITLE
Re. branch listing in the algorithm

### ISSUE THREAD

**Issue by macsharma** [zji90/TSCAN#1]
Dear Sir,
The following error pops up when I set the listbranch flag to True
neuralTSCANorder <- TSCANorder(neuralTSkmeans,orderonly = FALSE,listbranch=TRUE)
Error in if (is.numeric(v) && any(v < 0)) { : 
  missing value where TRUE/FALSE needed

if I do keep listbranch as FALSE, no such error pops up and code runs smoothly

**Comment by zji90** [comment]
Hi, 
This is likely to happen if your tree does not have any branch (i.e. there is only one main path). In this case please just run TSCANorder(neuralTSkmeans,orderonly = FALSE,listbranch=FALSE). I will update the function so that the error will not appear.
