### ISSUE TITLE
Error in svd(x, nu = 0, nv = k) : a dimension is zero

### ISSUE THREAD

**Issue by galaxyeee** [zji90/TSCAN#11]
Dear TSCAN developers,

I am writing because I have two questions. I saw the message to normalize the seurat object and entered the code after normalizing, but this error appeared.

`> s <- readRDS("/Users/eunhalim/Downloads/20220619_tastebuds_all_cluster_v2.rds")
> s <- SCTransform(s)
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 20853 by 11435
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 5000 cells
  |===========================================================| 100%
There are 11 estimated thetas smaller than 1e-07 - will be set to 1e-07
Found 123 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 20853 genes
  |===========================================================| 100%
Computing corrected count matrix for 20853 genes
  |===========================================================| 100%
Calculating gene attributes
Wall clock passed: Time difference of 1.930848 mins
Determine variable features
Place corrected count matrix in counts slot
Centering data matrix
  |===========================================================| 100%
Set default assay to SCT
> data_input  <- as.matrix(s@assays$SCT@data)
> procdata <- preprocess(data_input)
> lpsmclust <- exprmclust(procdata)
Error in svd(x, nu = 0, nv = k) : a dimension is zero
` 

Also, I wonder if there is no problem with the result without entering the start cluster.

Thank you,
LIM EUNHA

**Comment by zji90** [comment]
Hi,

I recommend not using preprocess() and go with the remaining steps.
