### ISSUE TITLE
v2.0 to Bioconductor

### ISSUE THREAD

**Issue by irzamsarfraz** [zji90/TSCAN#13]
Thanks to the developers for making this very useful tool. I am of the developers of the [singleCellTK](https://github.com/compbiomed/singleCellTK) toolkit that includes a number of tools for console or ui based analysis of single cell data and we have recently added support for trajectory analysis using TSCAN package. 

However, using the version available on Bioconductor (1.34) we run into some errors with the use of some deprecated functions from Matrix package. These errors seem to have been fixed with the 2.0 release available on github, but since to make sure that our singleCellTK package passes the bioconductor checks, we were hoping that the latest vesion of the TSCAN package would also be pushed to Bioconductor. 

We are not sure if the developers intend to do so or not but it would definitely be very helpful. Thank you!

**Comment by zji90** [comment]
Hi,

Thank you for your interest in TSCAN. We will update the TSCAN package on Bioconductor, but it may probably take some time since the email address linked to my account was terminated and I need to recover my account.

**Comment by zji90** [comment]
I have synched Bioconductor with Github version. Pls check (may take up to 24 hrs to reflect the changes).
