### ISSUE TITLE
TSCAN broken in development branch of Bioconductor

### ISSUE THREAD

**Issue by PeteHaitch** [zji90/TSCAN#14]
The version of **TSCAN** currently available on Bioconductor's development branch is broken: please see https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/TSCAN/

Taking a look at the the git logs of the Bioconductor git-hosted version, it looks like you may have accidentally clobbered a bunch of changes that were available on the Bioconductor git-hosted version that were not mirrored to the GitHub-hosted version when you made the changes in https://github.com/zji90/TSCAN/issues/13.

```sh
git clone https://git.bioconductor.org/packages/TSCAN
(master)*$ git log --summary HEAD...64483787c8d53e3d2913fd0f6af22b922ab0776d | cat
commit dbb1dfdccab085ca25e45d617554fd5e26b31e1e
Author: Zhicheng Ji <zhichengji@gmail.com>
Date:   Fri Sep 23 20:25:09 2022 -0400

    commit


commit 33a83908a11468d3cd412ba02ec7c7bdf1c4691f
Author: Zhicheng Ji <zhichengji@gmail.com>
Date:   Fri Sep 23 20:23:59 2022 -0400

    commit


commit 8b680d1a5750dcd0984e7e12d221e7bd729fcf7b
Author: Zhicheng Ji <zhichengji@gmail.com>
Date:   Fri Sep 23 20:23:04 2022 -0400

    commit

 create mode 100755 R/genedynamics.R
 create mode 100755 R/guided_MST.R
 create mode 100755 R/guided_tscan.R
 delete mode 100644 R/mapCellsToEdges.R
 delete mode 100644 R/orderCells.R
 delete mode 100644 R/perCellEntropy.R
 delete mode 100644 R/quickPseudotime.R
 delete mode 100644 R/reexports.R
 delete mode 100644 R/reportEdges.R
 delete mode 100644 R/testPseudotime.R
 delete mode 100644 inst/NEWS.Rd
 create mode 100644 inst/shiny/rsconnect/shinyapps.io/zhiji/TSCAN.dcf
 create mode 100644 inst/shiny/rsconnect/shinyapps.io/zhiji/shiny.dcf
 delete mode 100644 inst/shiny/shinyapps/zhiji/TSCAN.dcf
 mode change 100755 => 100644 inst/shiny/www/ajaxloaderq.gif
 mode change 100755 => 100644 inst/shiny/www/busy.js
 mode change 100755 => 100644 inst/shiny/www/style.css
 create mode 100644 man/genedynamics.Rd
 create mode 100644 man/guided_MST.Rd
 create mode 100644 man/guided_tscan.Rd
 delete mode 100644 man/mapCellsToEdges.Rd
 delete mode 100644 man/orderCells.Rd
 delete mode 100644 man/perCellEntropy.Rd
 delete mode 100644 man/quickPseudotime.Rd
 delete mode 100644 man/reexports.Rd
 delete mode 100644 man/reportEdges.Rd
 delete mode 100644 man/testPseudotime.Rd
 delete mode 100644 tests/testthat.R
 delete mode 100644 tests/testthat/test-entropy.R
 delete mode 100644 tests/testthat/test-mapping.R
 delete mode 100644 tests/testthat/test-order.R
 delete mode 100644 tests/testthat/test-quick.R
 delete mode 100644 tests/testthat/test-report.R
 delete mode 100644 tests/testthat/test-test.R
 create mode 100644 vignettes/guided_tscan.pdf
```

Note the large number of changes in commit `8b680d1a5750dcd0984e7e12d221e7bd729fcf7b`, including deletion of a number of files.

This has undone all the work @LTLA put into improving **TSCAN** for inclusion in Bioconductor (https://github.com/zji90/TSCAN/issues/9) and has also broken the use of **TSCAN** featured in 'Orchestrating Single Cell Analysis with Bioconductor' book (e.g., the material in https://bioconductor.org/books/3.16/OSCA.multisample/merged-hsc.html#combined-analyses no longer works because these changes have also removed the `TSCAN::quickPseudotime()` function).

Will you be able to fix this before the October 28, which is the deadline for the next release (https://bioconductor.org/developers/release-schedule/)?

**Comment by zji90** [comment]
Hi Peter,

I am sorry the recent update has caused a bunch of problems. I intended to
fix another problem but was not aware that it caused many more problems. I
am not quite familiar with the current Bioconductor submission system and
may not have the time to learn and explore the system. Is it possible for
Bioconductor to just undo my recent update and revert to the last version
that works (the version that has @LTLA's improvement)? Thanks!


Best,
Jason

--
Zhicheng Ji, PhD.
Assistant Professor
Department of Biostatistics and Bioinformatics
Duke University School of Medicine
2424 Erwin Road, Suite 1102 Hock Plaza Box 2721
Durham, NC 27710, USA

**Comment by PeteHaitch** [comment]
Hi Jason,

That's okay, I realise it was unintentional. 
Git is not the easiest tool to use!
I suggest emailing bioc-devel@r-project.org to ask for advice on how to fix this and roll-back to the previous version.

Cheers,
Pete

**Comment by zji90** [comment]
Hi Peter,

I think I should have fixed the issue by reverting the whole package back
to a previous version. Let me know if this works.


Best,
Jason

--
Zhicheng Ji, PhD.
Assistant Professor
Department of Biostatistics and Bioinformatics
Duke University School of Medicine
2424 Erwin Road, Suite 1102 Hock Plaza Box 2721
Durham, NC 27710, USA

**Comment by PeteHaitch** [comment]
Hi Jason,

Thank you promptly taking care of this.
**TSCAN** is now building again on BioC 3.16 (https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/TSCAN/)!
And this enables OSCA to build again.

Thanks,
Pete
