### ISSUE TITLE
Adding Custom color to the plotmclust

### ISSUE THREAD

**Issue by SmritiChawla** [zji90/TSCAN#5]
Hi

How I can add custom colors to cells using plotmclust()

Thanks & Regards
Smriti

**Comment by zji90** [comment]
Hi Smriti,
You can do something like this:

plotmclust(lpsmclust) +
scale_color_manual(values=c('red','magenta','purple'))

You can change c('red','magenta','purple') to any color you want. The
number of elements in values should be the same as the number of clusters.


Best,
Jason

--
Zhicheng Ji
PhD Candidate Department of Biostatistics
M.S.E Student Department of Computer Science
Johns Hopkins University

**Comment by SmritiChawla** [comment]
Thank you so very much.
RegardsSmriti

Sent from Yahoo Mail on Android 
 
  On Mon, 11 Feb 2019 at 2:04 AM, Zhicheng Ji<notifications@github.com> wrote:   Hi Smriti,
You can do something like this:

plotmclust(lpsmclust) +
scale_color_manual(values=c('red','magenta','purple'))

You can change c('red','magenta','purple') to any color you want. The
number of elements in values should be the same as the number of clusters.


Best,
Jason

--
Zhicheng Ji
PhD Candidate Department of Biostatistics
M.S.E Student Department of Computer Science
Johns Hopkins University
