### ISSUE TITLE
<!doctype html> <!--[if lt IE 7 ]> <html  ERROR when uploading data to TSCAN website

### ISSUE THREAD

**Issue by jhemela** [zji90/TSCAN#6]
Hi there, 

When I try to upload my matrix data to the website, I get the error "<!doctype html> <!--[if lt IE 7 ]> <html" in the loading box...

Any advice as to how to solve this error?

**Comment by zji90** [comment]
This is probably because the UI is not supported in IE7. You can switch to other explorers like Chrome and give it a try.
