### ISSUE TITLE
How to upgrade to TSCAN ver 1.7.0

### ISSUE THREAD

**Issue by Enolia** [zji90/TSCAN#7]
Hi!

I can install TSCAN from github.
But, I don't know how to upgrade to ver.1.7.0.
Please tell me.

Thanks

**Comment by zji90** [comment]
Hi Enolia,
I don't know whether you have any specific reason to upgrade to ver.1.7.0 but the github version is always the most updated version. It will be helpful if you could provide more information about the ver1.7.0 (e.g. where you find this version)

**Comment by Enolia** [comment]
Dear zji90,
I'm sorry. I have several mistakes. I want most updated version, and installed using 

BiocManager::install("TSCAN")

Then got most updated version TSCAN ver 1.22.0.
I did not confirm but it may be installed by github.
But, I run TSCANui(), user interface version is 1.0.0. User interface can not be updated? Please see attachment image.
Should I  avoid using TSCANui() when I wanna use most updated version?

This is my PC environments
R 3.6.1 on windows 10
16 GB memory

Many many thanks
![無題](https://user-images.githubusercontent.com/53217990/66284999-a098fd80-e905-11e9-944a-ba3037e4ca9e.png)

**Comment by zji90** [comment]
Hi,
Sorry only the TSCAN command line software package is updated to 1.7.0. The user interface hasn't been upgraded since the publication of the paper. The software package and the user interface has two different versions.
