### ISSUE TITLE
What values would you recommend for preprocess on droplet-based UMI data?

### ISSUE THREAD

**Issue by lucygarner** [zji90/TSCAN#8]
Hi,

I was wondering what values you would recommend for minexpr_value, minexpr_percent and cvcutoff for preprocessing 10x Genomics UMI count data?

Many thanks,
Lucy

**Comment by zji90** [comment]
Hi Lucy,
Thanks for your interest. For 10x data I would recommend setting minexpr_value=0 and minexpr_percent=0.1 and cvcutoff=0.1. Note that you need to do library size normalization before running this function.

**Comment by lucygarner** [comment]
Hi,

Thanks.  Is it correct to use the "pbmcs@assays$SCT@data" slot from a Seurat object if I am using sctransform normalization and then run preprocess() on this?

As a separate question, is there a function within TSCAN to nicely plot a heatmap of the genes that are differentially expressed along the pseudotime axis?

Best wishes,
Lucy

**Comment by zji90** [comment]
Please consult Seurat for the current data slot to use.

TSCAN does not have a heatmap plotting function. Please check pheatmap or ComplexHeatmap.

**Comment by lucygarner** [comment]
Thank you - the slot I mentioned would be data normalised with SCTransform.
